import '../globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { Providers } from "./providers"



const monserrat = Montserrat({
    display: "swap",
    weight: "400",
    subsets: ["latin"],
    variable: "--font-sans"
});

export const metadata: Metadata = {
    title: 'Authentication®',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className="dark">
            <body className={monserrat.className}>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    )
}
